version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - TZ=Asia/Jakarta
      - N8N_PORT=5678
      - WEBHOOK_URL=https://4afa-114-10-47-129.ngrok-free.app
    volumes:
      - ./n8n:/home/node/.n8n
