name: Deploy n8n Workflows

on:
  push:
    paths:
      - "workflows/*.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Clean and deploy workflows to n8n
        env:
          N8N_URL: ${{ secrets.N8N_URL }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        run: |
          for file in workflows/*.json; do
            echo "Processing $file..."

            # Remove disallowed fields before POST
            jq 'del(.id, .versionId, .webhookId, .meta)' "$file" > cleaned.json

            echo "Posting cleaned workflow to $N8N_URL"
            curl -X POST "$N8N_URL/rest/workflows" \
              -H "Authorization: Bearer $N8N_API_KEY" \
              -H "Content-Type: application/json" \
              --data-binary @cleaned.json

            rm cleaned.json
          done
