name: Deploy to n8n

on:
workflow_dispatch: # ⬅️ Ini penting untuk memunculkan tombol "Run workflow"

jobs:
deploy:
runs-on: ubuntu-latest
    steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Install jq
    run: |
      sudo apt-get update
      sudo apt-get install -y jq

  - name: Deploy each workflow to n8n
    env:
      N8N_API_URL: ${{ secrets.N8N_API_URL }}
      N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
    run: |
      for file in workflows/*.json; do
        echo "Deploying $file..."

        NAME=$(jq -r .name "$file")

        # Cek apakah workflow sudah ada
        EXISTING_ID=$(curl -s "$N8N_API_URL/workflows" \
          -H "Authorization: Bearer $N8N_API_KEY" \
          | jq -r ".data[] | select(.name==\"$NAME\") | .id")

        if [ -n "$EXISTING_ID" ]; then
          echo "🔁 Updating: $NAME"
          curl -s -X PUT "$N8N_API_URL/workflows/$EXISTING_ID" \
            -H "Authorization: Bearer $N8N_API_KEY" \
            -H "Content-Type: application/json" \
            --data @"$file"
        else
          echo "🆕 Creating new workflow: $NAME"
          curl -s -X POST "$N8N_API_URL/workflows" \
            -H "Authorization: Bearer $N8N_API_KEY" \
            -H "Content-Type: application/json" \
            --data @"$file"
        fi
      done
