name: Deploy Workflows to n8n

on:
  push:
    paths:
      - workflows/*.json
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Deploy workflows to self-hosted n8n
        env:
          N8N_API_URL: ${{ secrets.N8N_API_URL }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        run: |
          for file in workflows/*.json; do
            NAME=$(jq -r .name "$file")
            echo "🚀 Deploying $NAME from $file"

            # Bersihkan file JSON dari field yang tidak boleh dikirim
            CLEANED_FILE="cleaned-$(basename "$file")"
            jq 'del(.id, .versionId, .webhookId, .meta)' "$file" > "$CLEANED_FILE"

            # Cek apakah workflow sudah ada
            WORKFLOW_ID=$(curl -s "$N8N_API_URL/workflows" \
              -H "Authorization: Bearer $N8N_API_KEY" \
              | jq -r ".data[] | select(.name==\"$NAME\") | .id")

            if [ -n "$WORKFLOW_ID" ]; then
              echo "🔄 Updating $NAME..."
              curl -s -X PUT "$N8N_API_URL/workflows/$WORKFLOW_ID" \
                -H "Authorization: Bearer $N8N_API_KEY" \
                -H "Content-Type: application/json" \
                --data @"$CLEANED_FILE"
            else
              echo "🆕 Creating $NAME..."
              curl -s -X POST "$N8N_API_URL/workflows" \
                -H "Authorization: Bearer $N8N_API_KEY" \
                -H "Content-Type: application/json" \
                --data @"$CLEANED_FILE"
            fi

            # Opsional: Hapus file sementara
            rm "$CLEANED_FILE"
          done
